import pygame

pygame.font.init()


#Circle Constants
CIRCLE_COLOR = pygame.Color(34, 33, 33)
CIRCLE_RADIUS = 15

#Text Constants
TEXT_UWWRITTEN = pygame.Color(0, 0, 0)
TEXT_WRITTEN = pygame.Color(0, 255, 0)
TEXT_BACKGROUND = pygame.Color(255, 255, 255, 0)

FONT = pygame.font.SysFont("arial", size=18, bold=True)

word_list = [
    "wie", "ich", "seine", "dass", "er", "war", "für", "auf", "sind", "mit",
    "sie", "sein", "bei", "ein", "haben", "dies", "aus", "durch", "heiß", "Wort",
    "aber", "was", "einige", "ist", "es", "Sie", "oder", "hatte", "die", "von",
    "zu", "und", "wir", "können", "andere", "waren", "tun", "ihre", "Zeit", "wenn",
    "werden", "sagte", "jeder", "sagen", "tut", "Satz", "drei", "wollen", "Luft", "gut",
    "auch", "spielen", "klein", "Ende", "setzen", "Zuhause", "lesen", "seits", "Hafen", "groß",
    "buchstabieren", "hinzufügen", "Lande", "hier", "muss", "hoch", "so", "folgen", "Akt", "warum",
    "fragen", "Männer", "Veränderung", "ging", "Licht", "Art", "müssen", "Haus", "Bild", "versuchen",
    "uns", "wieder", "Tier", "Punkt", "Mutter", "Welt", "bauen", "selbst", "Erde", "Vater",
    "neu", "Arbeit", "Teil", "nehmen", "erhalten", "Ort", "gemacht", "leben", "wo", "nach",
    "zurück", "wenig", "nur", "Runde", "Mann", "Jahr", "kam", "zeigen", "mir", "geben",
    "unsere", "unter", "Name", "sehr", "Formular", "denken", "Hilfe", "niedrig", "Linie", "abweichen",
    "wiederum", "Ursache", "viel", "bedeuten", "vor", "Umzug", "Recht", "Junge", "alt", "gleich",
    "alle", "da", "oben", "Verwendung", "Ihre", "Weg", "über", "viele", "dann", "schreiben",
    "würde", "diese", "lange", "machen", "Sache", "sehen", "ihm", "zwei", "hat", "suchen",
    "mehr", "Tag", "könnte", "gehen", "kommen", "tat", "Anzahl", "klingen", "nicht", "Menschen",
    "meine", "wissen", "Wasser", "als", "Anruf", "erste", "unten", "Seite", "gewesen", "jetzt",
    "finden", "Kopf", "stehen", "besitzen", "sollte", "Land", "gefunden", "Antwort", "Schule", "wachsen",
    "Studie", "noch", "lernen", "Anlage", "Abdeckung", "Lebensmittel", "Sonne", "vier", "zwischen", "Zustand",
    "halten", "Auge", "nie", "letzte", "lassen", "Gedanken", "Stadt", "Baum", "überqueren", "Bauernhof",
    "schwer", "Beginn", "Macht", "Geschichte", "Säge", "weit", "Meer", "ziehen", "links", "spät",
    "laufen", "während", "Presse", "Schließen", "Nacht", "realen", "Leben", "wenige", "Norden", "Buch",
    "tragen", "nahm", "Wissenschaft", "essen", "Zimmer", "Freund", "begann", "Idee", "Fisch", "berg",
    "Stopp", "einmal", "Basis", "hören", "Pferd", "Schnitt", "sicher", "beobachten", "Farbe", "Gesicht",
    "Holz", "Haupt-", "geöffnet", "scheinen", "zusammen", "nächste", "weiß", "Kinder", "Start", "bekam",
    "Beispiel", "erleichtern", "Papier", "Gruppe", "immer", "Musik", "diejenigen", "beide", "Marke", "oft",
    "Schreiben", "bis", "Meile", "Fluss", "Auto", "Füße", "Pflege", "zweite", "genug", "Ebene",
    "Mädchen", "üblich", "jung", "bereit", "je", "rot", "Liste", "obwohl", "fühlen", "Vortrag",
    "Vogel", "bald", "Körper", "Hund", "Familie", "direkt", "Pose", "verlassen", "Lied", "messen",
    "Tür", "Produkt", "schwarz", "kurz", "Zahl", "Klasse", "Wind", "Frage", "passieren", "vollständig",
    "Schiff", "Bereich", "Hälfte", "Stein", "bestellen", "Feuer", "Süden", "Problem", "Stück", "wusste",
    "seit", "obere", "ganze", "König", "Straße", "Zoll", "multiplizieren", "nichts", "Kurs", "bleiben",
    "Rad", "voll", "Kraft", "blau", "Objekt", "entscheiden", "Oberfläche", "tief", "Mond", "Insel",
    "Fuß", "System", "beschäftigt", "Prüfung", "Rekord", "Boot", "gemeinsam", "goldenen", "möglich", "Flugzeug",
    "statt", "trocken", "Wunder", "Lachen", "tausend", "lief", "überprüfen", "Spiel", "Form", "gleichsetzen",
    "Fehl", "gebracht", "Wärme", "Schnee", "Reifen", "bringen", "ja", "entfernt", "füllen", "Osten",
    "malen", "Sprache", "Einheit", "fein", "fliegen", "fallen", "führen", "Schrei", "dunkel", "Maschine",
    "note", "warten", "Plan", "Abbildung", "Stern", "Kasten", "Nomen", "Feld", "Rest", "richtig",
    "fähig", "Pfund", "getan", "Schönheit", "Antriebs", "stand", "enthalten", "Front", "lehren", "Woche",
    "Finale", "gab", "grün", "oh", "schnell", "entwickeln", "Ozean", "warme", "kostenlos", "Minute",
    "stark", "besondere", "Geist", "hinter", "klar", "Schwanz", "produzieren", "Tatsache", "Raum", "gehört",
    "beste", "Stunde", "besser", "wahr", "hundert", "fünf", "merken", "Schritt", "früh", "Westen",
    "Boden", "Interesse", "erreichen", "Verbum", "singen", "sechs", "Tabelle", "Reise", "weniger", "Morgen",
    "zehn", "einfach", "mehrere", "Vokal", "Krieg", "legen", "gegen", "Muster", "schleppend", "Zentrum",
    "Liebe", "Person", "Geld", "dienen", "erscheinen", "Karte", "regen", "Regel", "regieren", "Kälte",
    "Hinweis", "Stimme", "Energie", "Jagd", "wahrscheinlich", "Bett", "Bruder", "Ei", "Fahrt", "Zelle",
    "glauben", "vielleicht", "pflücken", "plötzlich", "zählen", "Platz", "Grund", "Dauer", "vertreten", "Kunst",
    "Thema", "Region", "Größe", "variieren", "regeln", "sprechen", "Gewicht", "allgemein", "Eis", "Materie",
    "Kreis", "Paar", "umfassen", "Kluft", "Silbe", "Filz", "Kugel", "Welle", "Herz", "Uhr",
    "vorhanden", "Tanz", "Motor", "Position", "Arm", "breit", "Segel", "Material", "Fraktion", "Wald",
    "sitzen", "Rennen", "Fenster", "Speicher", "Sommer", "Zug", "Schlaf", "beweisen", "einsam", "Bein",
    "Übung", "Wand", "Fang", "Berg", "wünschen", "Himmel", "Board", "Freude", "Winter", "sa",
    "geschrieben", "wilden", "Instrument", "gehalten", "Glas", "Gras", "Kuh", "Rand", "Zeichen", "Besuch",
    "Vergangenheit", "weich", "Spaß", "hell", "Gases", "Wetter", "Monat", "Million", "Finish", "glücklich",
    "hoffen", "blume", "kleiden", "seltsam", "Vorbei", "Handel", "Melodie", "Büro", "empfangen", "Reihe",
    "Mund", "genau", "sterben", "wenigsten", "Ärger", "außer", "schrieb", "Samen", "Ton", "beitreten",
    "vorschlagen", "sauber", "Pause", "Dame", "Hof", "steigen", "schlecht", "Schlag", "Öl", "Blut",
    "berühren", "wuchs", "Cent", "mischen", "Mannschaft", "Draht", "Kosten", "verloren", "braun", "Garten",
    "gesendet", "wählen", "fiel", "passen", "fließen", "Messe", "Bank", "sammeln", "sparen", "Kontrolle",
    "dezimal", "Ohr", "sonst", "ganz", "pleite", "Fall", "Mitte", "töten", "Sohn", "See",
    "Moment", "Maßstab", "laut", "Frühling", "Kind", "gerade", "Konsonant", "Nation", "Wörterbuch", "milch",
    "Geschwindigkeit", "Verfahren", "Orgel", "zahlen", "Alter", "Abschnitt", "Kleid", "Wolke", "Überraschung", "ruhig",
    "winzig", "Aufstieg", "kühlen", "Entwurf", "arm", "Menge", "Versuch", "Schlüssel", "Eisen", "Einzel",
    "Stick", "Wohnung", "zwanzig", "Haut", "Lächeln", "Falte", "Loch", "springen", "acht", "Dorf",
    "treffen", "Wurzel", "kaufen", "erhöhen", "lösen", "Metall", "ob", "drücken", "sieben", "Absatz",
    "dritte", "wird", "Hand", "Haar", "beschreiben", "Koch", "entweder", "Ergebnis", "brennen", "Hügel",
    "Katze", "Jahrhundert", "betrachten", "Typ", "Gesetz", "Bit", "Küste", "Kopie", "Ausdruck", "still",
    "Sand", "Rolle", "Temperatur", "Finger", "Industrie", "Wert", "Kampf", "Lüge", "schlagen", "begeistern",
    "natürlich", "Blick", "Sinn", "Hauptstadt", "Stuhl", "Achtung", "Obst", "reich", "dick", "Soldat",
    "Prozess", "betreiben", "Praxis", "trennen", "schwierig", "Arzt", "Bitte", "schützen", "Mittag", "Ernte",
    "modernen", "Elementes", "Schüler", "Ecke", "Partei", "Versorgung", "deren", "lokalisieren", "Rings", "Charakter",
    "insekt", "gefangen", "Funk", "Speiche", "Atom", "Mensch", "Wirkung", "elektrisch", "erwarten", "Knochen",
    "Schiene", "vorstellen", "bieten", "zustimmen", "sanft", "Frau", "Kapitän", "erraten", "erforderlich", "scharf",
    "Flügel", "schaffen", "Nachbar", "Wasch", "Fledermaus", "eher", "mais", "vergleichen", "Gedicht", "Schnur",
    "Glocke", "abhängen", "Fleisch", "einreiben", "Rohr", "berühmt", "Dollar", "Strom", "Angst", "dünn",
    "Dreieck", "Eile", "Chef", "Kolonie", "Mine", "Krawatie", "eingeben", "Dur", "frisch", "Suche",
    "senden", "gelb", "Pistole", "erlauben", "Druck", "tot", "Stelle", "Wüste", "Anzug", "Aufzug",
    "stiegen", "ankommen", "Stamm", "Spur", "Elternteil", "Ufer", "Teilung", "Blatt", "Substanz", "begünstigen",
    "verbinden", "verbringen", "Akkord", "Fett", "froh", "Original", "Aktie", "Station", "Papa", "Brot",
    "aufladen", "Leiste", "Angebot", "Segment", "Sklave", "ente", "Augenblick", "Markt", "Grad", "besiedeln",
    "küken", "liebe", "Feind", "antworten", "Getränk", "auftreten", "Unterstützung", "Rede", "Natur", "Dampf",
    "Bewegung", "Flüssigkeit", "protokollieren", "gemeint", "Quotient", "Gebiss", "Schale", "Hals", "Sauerstoff", "Zucker",
    "Tod", "ziemlich", "Geschicklichkeit", "Frauen", "Saison", "Lösung", "Magnet", "Silber", "danken", "Zweig",
    "Suffix", "insbesondere", "Feige", "ängstlich", "riesig", "Schwester", "Stahl", "diskutieren", "vorwärts", "ähnlich",
    "Erfahrung", "Partitur", "apfel", "gekauft", "geführt", "Tonhöhe", "Mantel", "Masse", "Band", "Seil",
    "Rutsch", "gewinnen", "träumen", "Abend", "Futtermittel", "Werkzeug", "gesamt", "Geruch", "Tal", "doppelt",
    "Sitz", "fortsetzen", "Block", "Hut", "verkaufen", "Erfolg", "Firma", "subtrahieren", "Veranstaltung", "schwimmen",
    "Begriff", "Gegenteil", "Schuh", "Schulter", "Verbreitung", "arrangieren", "Lager", "erfinden", "Baumwolle", "geboren",
    "bestimmen", "Quart", "neun", "Lastwagen", "Lärm", "Chance", "Geschäft", "Stretch", "werfen", "Glanz",
    "Immobilien", "Spalte", "Molekül", "falsch", "grau", "Wiederholung", "erfordern", "vorbereiten", "Salz", "Nase",
    "Zorn", "Anspruch", "Kontinent"
]